apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sgx-deviceplugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: sgx-deviceplugin
  template:
    metadata:
      labels:
        app: sgx-deviceplugin
    spec:
      containers:
      - name: sgx-deviceplugin
        image: sebvaucher/sgx-deviceplugin:0.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: devisgx
          mountPath: /dev/isgx
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devisgx
        hostPath:
          path: /dev/isgx
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
